### ISSUE TITLE
Images are too large.

### ISSUE THREAD

**Issue by AlexanderOtavka** [DHSDevelopersClub/club-website#16]
Many images such as the python image are too high resolution for the actual size on screen, it slows down page load.  The fullbleed images are ok, but the smaller assets need to be scaled down.

**Comment by SebastianBoyd** [comment]
I fixed the python image in commit 8bfbf3b03c3eb499b1016cd73c092226715d01bc. It is now a 5k svg.

**Comment by SebastianBoyd** [comment]
We should use responsive images as not to serve a low res image on screens that can display them. Here is a good article on implementing them https://jakearchibald.com/2015/anatomy-of-responsive-images/.

**Comment by AlexanderOtavka** [comment]
Good find.  This isn't top priority, but we should definitely do this eventually.

**Comment by krashanoff** [comment]
I'll take a look into it

**Comment by SebastianBoyd** [comment]
Resized some of the largest images to reasonable sizes but we still need to add responsiveness.
