### ISSUE TITLE
Responsive Sizing Erros 

### ISSUE THREAD

**Issue by SebastianBoyd** [DHSDevelopersClub/club-website#19]
On my desktop computer with the window filling the screen the site decided to choose the mobile version of the site:
![problem](https://cloud.githubusercontent.com/assets/9423201/9709448/b55650be-54e0-11e5-99ab-d77a0e4de22f.jpg)

**Comment by AlexanderOtavka** [comment]
That's bizzarre.  Can you reproduce on a local server?

**Comment by SebastianBoyd** [comment]
@AlexanderOtavka Its working fine from my local server

**Comment by SebastianBoyd** [comment]
I cleared my cache and it works fine I don't know what happened and ill reopen this issue if it happens again
