### ISSUE TITLE
Scroll element doesn't scroll down enough.

### ISSUE THREAD

**Issue by duncangrubbs** [DHSDevelopersClub/club-website#49]

**Comment by AlexanderOtavka** [comment]
When exactly is this happening? I don't see it on my phone or computer.

**Comment by duncangrubbs** [comment]
On my computer if I click the button it cuts off the two bottom bios.

**Comment by maxostarr** [comment]
It seems like the scroll element scrolls to the align the top of the `<h1 class="content">About</h1>` with the top of the viewport. The bottom bois get cut off, it's because your viewport isn't tall enough to display all of them.

**Comment by SebastianBoyd** [comment]
@manmon42  is right and I talked to @duncangrubbs
